### PR TITLE
fix for hexo3

### PR DESCRIPTION
**Pull request by Gtskk**
Fix for hexo3 support

### CODE REVIEW

**Comment by sergiolepore** [comment]
Thanks! I'll be testing it (I'm not using Hexo v3 ATM, so it may take me some time) and if everything is OK, I'll release a new version.
I'll keep you updated.

:smile:

**Comment by Gtskk** [comment]
OK

**Comment by s10wen** [comment]
Hey @sergiolepore I've tested this and confirm it works https://github.com/sergiolepore/hexo-tag-emojis/issues/9#issuecomment-140660882

**Comment by sergiolepore** [comment]
@s10wen thank you so much and sorry for the late response. I'll release a new version later today :smile:

**Comment by Gtskk** [comment]
OK

**Pull request merged**
